[project]
name = "mcp-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.10.1",
    "nest-asyncio>=1.6.0",
    "openai>=1.93.0",
    "python-dotenv>=1.1.1",
]
